version: '3'                               #Version vom docker-Compose file

volumes:
   db-data:

services:                                  #Die Services, welche wir erstellt haben
   db:                                     #Datenbank Server
     image: mysql-server:8.0.1             #Image Name
     volumes:
       - db-data:/var/lib/mysql
     ports:
       - "3306:3306"                      #Der Port, auf dem MySql Server lauft
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mypass123     #DB-User Password
       MYSQL_DATABASE: mysql              #DB Name
       MYSQL_USER: root                   #DB User
       MYSQL_PASSWORD: mypass123          #DB-User Passwort


   phpmyadmin:                            #Phpmyadmin Service
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin          #Image Name
    restart: always 
    ports:                                
      - '8081:80'                         #Der Port, auf dem Phpmyadmin lauft
    environment:
      PMA_HOST: db                        #Service Umgebung -> DB
      MYSQL_ROOT_PASSWORD: mypass123ver   #Phpmyadmin Passwort
